version: '2'

services:

  client:
    image: "node:16"
    user: "node"
    working_dir: /usr/src/app      
    volumes:
      - .:/usr/src/app
    environment:
      FAST_REFRESH: "true"
      WDS_SOCKET_PORT: 3002
      # CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3001:3000"
      - "3002:3000"
    expose:
      - "3001"
    command: "npm start"
    # stdin_open: true
    # tty: true